"""add user identities

Revision ID: 11227a56799d
Revises: 984e8d43a8e7
Create Date: 2026-01-30 00:37:28.482584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11227a56799d'
down_revision: Union[str, Sequence[str], None] = '984e8d43a8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('local', 'google', name='auth_provider_enum'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_index(op.f('ix_user_identities_id'), 'user_identities', ['id'], unique=False)
    op.drop_constraint(op.f('users_password_key'), 'users', type_='unique')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_password_key'), 'users', ['password'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_identities_id'), table_name='user_identities')
    op.drop_table('user_identities')
    # ### end Alembic commands ###
