"""change jti type in refresh_token to uuid

Revision ID: e7ebdb6a6c11
Revises: 4a54d6072c46
Create Date: 2026-02-19 00:26:13.852758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ebdb6a6c11'
down_revision: Union[str, Sequence[str], None] = '4a54d6072c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='jti::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               postgresql_using='jti::text')
    # ### end Alembic commands ###
